import { afterEach, beforeAll, describe, expect, it } from "vitest";
import { and, eq } from "drizzle-orm";
import { db, schema } from "@/infrastructure/db/client";
import { registerConnector } from "@/infrastructure/connectors/registry";
import { completeScrapeRequest } from "./complete-scrape-request";
import { resetDb } from "@/test/integration/db-helpers";
import type { RemoteDataset, RemoteItemPage, SourceConnector } from "@/domain/sync/ports";

/**
 * Fake standing in for the real Apify dataset-read connector — registered under
 * the real "apify" kind (unlike `sync-dataset.integration.test.ts`'s "manual"
 * fake) because `completeScrapeRequest` always creates its source row with
 * `kind: "apify"`, so `syncDataset` resolves the connector for that kind.
 */
function fakeApifyConnector(items: Record<string, unknown>[]): SourceConnector {
  return {
    kind: "apify",
    async listDatasets(): Promise<RemoteDataset[]> {
      return [];
    },
    async getDataset(externalId: string): Promise<RemoteDataset | null> {
      return {
        externalId,
        name: "fake",
        title: "fake",
        itemCount: items.length,
        createdAt: new Date("2026-01-01T00:00:00.000Z"),
        modifiedAt: new Date("2026-01-01T00:00:00.000Z"),
        producerId: null,
        producerRunId: null,
      };
    },
    async fetchItems(_externalId: string, offset: number, limit: number): Promise<RemoteItemPage> {
      const page = items.slice(offset, offset + limit);
      return { items: page, total: items.length, offset, limit };
    },
  };
}

async function seedCompanyTemplateAndRequest(apifyRunId: string) {
  const [company] = await db()
    .insert(schema.companies)
    .values({ name: `Complete Test Co ${crypto.randomUUID()}`, slug: `complete-test-${crypto.randomUUID()}` })
    .returning();

  const [template] = await db()
    .insert(schema.actorTemplates)
    .values({
      name: `Complete Test Template ${crypto.randomUUID()}`,
      platform: "instagram",
      requirementKind: "hashtag_search",
      actorId: "apify/instagram-scraper",
      requiredParams: ["directUrls"],
    })
    .returning();

  // apify/n8n-sourced mapping profile so ingested items actually normalize into leads —
  // proof the webhook wires into the *real* validate+store pipeline, not a stub.
  await db()
    .insert(schema.mappingProfiles)
    .values({
      name: `complete-test-profile-${crypto.randomUUID()}`,
      sourceKind: "apify",
      rules: {
        externalId: { from: ["id"] },
        body: { from: ["text"] },
        postedAt: { from: ["time"], transform: "toIso8601" },
      },
      matchPaths: ["id", "text"],
      passthrough: true,
      autoGenerated: false,
      confidence: 1,
      approvedAt: new Date(),
    });

  const [scrapeRequest] = await db()
    .insert(schema.scrapeRequests)
    .values({
      companyId: company.id,
      actorTemplateId: template.id,
      templateName: template.name,
      platform: template.platform,
      requirementKind: template.requirementKind,
      actorId: template.actorId,
      params: { directUrls: ["https://instagram.com/x"] },
      paramsFingerprint: "fixed",
      status: "running",
      apifyRunId,
    })
    .returning();

  return { companyId: company.id, template, scrapeRequest };
}

describe("completeScrapeRequest", () => {
  beforeAll(async () => {
    await resetDb();
  });
  afterEach(async () => {
    await resetDb();
  });

  it("returns unhandled for a run id that doesn't match a triggered scrape request", async () => {
    const result = await completeScrapeRequest({ apifyRunId: "unknown-run", status: "SUCCEEDED" });
    expect(result.handled).toBe(false);
  });

  it("wires a succeeded run's dataset into the real sync pipeline: source, dataset, raw records and leads", async () => {
    const { companyId, template, scrapeRequest } = await seedCompanyTemplateAndRequest("run-succeed-1");
    registerConnector(
      fakeApifyConnector([
        { id: "p1", text: "Looking to buy a villa in Canggu, budget 500k", time: "2026-01-01T00:00:00Z" },
      ]),
    );

    const result = await completeScrapeRequest({
      apifyRunId: "run-succeed-1",
      status: "SUCCEEDED",
      defaultDatasetId: "fake-ds-1",
      usageTotalUsd: 0.42,
      finishedAt: new Date().toISOString(),
    });

    expect(result.handled).toBe(true);
    expect(result.datasetId).toBeDefined();

    const [row] = await db().select().from(schema.scrapeRequests).where(eq(schema.scrapeRequests.id, scrapeRequest.id));
    expect(row.status).toBe("succeeded");
    expect(row.apifyDatasetId).toBe("fake-ds-1");
    expect(row.usageUsd).toBe(0.42);
    expect(row.sourceId).toBeTruthy();
    expect(row.datasetId).toBeTruthy();
    expect(row.itemCount).toBeGreaterThan(0);

    const [source] = await db()
      .select()
      .from(schema.sources)
      .where(and(eq(schema.sources.companyId, companyId), eq(schema.sources.name, `Apify — ${template.name}`)));
    expect(source).toBeTruthy();
    expect(source.kind).toBe("apify");

    const [dataset] = await db().select().from(schema.datasets).where(eq(schema.datasets.externalId, "fake-ds-1"));
    expect(dataset).toBeTruthy();
    // A triggered run's dataset is a one-off snapshot, not a recurring poll target.
    expect(dataset.autoSyncEnabled).toBe(false);

    const leads = await db().select().from(schema.leads).where(eq(schema.leads.companyId, companyId));
    expect(leads.length).toBeGreaterThan(0);
  });

  it("is idempotent — a repeated webhook for the same run reuses the same source/dataset instead of duplicating them", async () => {
    const { scrapeRequest } = await seedCompanyTemplateAndRequest("run-succeed-2");
    registerConnector(fakeApifyConnector([{ id: "p1", text: "hello", time: "2026-01-01T00:00:00Z" }]));

    const payload = {
      apifyRunId: "run-succeed-2",
      status: "SUCCEEDED" as const,
      defaultDatasetId: "fake-ds-2",
      usageTotalUsd: 0.1,
      finishedAt: new Date().toISOString(),
    };

    const first = await completeScrapeRequest(payload);
    const second = await completeScrapeRequest(payload);

    expect(first.datasetId).toBe(second.datasetId);
    const sources = await db().select().from(schema.sources);
    const datasets = await db().select().from(schema.datasets).where(eq(schema.datasets.externalId, "fake-ds-2"));
    expect(sources.filter((s) => s.name.includes(scrapeRequest.templateName))).toHaveLength(1);
    expect(datasets).toHaveLength(1);
  });

  it("records a failed run's status without touching source/dataset wiring", async () => {
    await seedCompanyTemplateAndRequest("run-fail-1");

    const result = await completeScrapeRequest({ apifyRunId: "run-fail-1", status: "FAILED" });

    expect(result.handled).toBe(true);
    expect(result.datasetId).toBeUndefined();
    const [row] = await db().select().from(schema.scrapeRequests).where(eq(schema.scrapeRequests.apifyRunId, "run-fail-1"));
    expect(row.status).toBe("failed");
    expect(row.sourceId).toBeNull();
    expect(row.datasetId).toBeNull();
  });
});
