import { Suspense } from "react";
import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { format } from "date-fns";
import { ArrowLeft } from "lucide-react";
import { requireAdmin } from "@/application/auth/current-user";
import { getDatasetDetail, getSyncEvents } from "@/application/datasets/dataset-queries";
import type { SchemaDiff } from "@/domain/dataset/types";
import { PageHeader } from "@/components/common/page-header";
import { HealthPill } from "@/components/common/health-pill";
import { RelativeTime } from "@/components/common/relative-time";
import { TableSkeleton } from "@/components/common/table-skeleton";
import { DataTable, DataTableHead } from "@/components/common/data-table";
import { EmptyState } from "@/components/common/empty-state";
import { formatCount } from "@/shared/format";
import { DatasetDetailActions } from "@/features/datasets/components/dataset-detail-actions";
import { SyncIntervalForm } from "@/features/datasets/components/sync-interval-form";
import { SyncRunsTable } from "@/features/datasets/components/sync-runs-table";
import { SyncEventsLog } from "@/features/datasets/components/sync-events-log";
import {
  AcceptSchemaVersionButton,
  ApproveMappingProfileButton,
} from "@/features/datasets/components/dataset-review-actions";

type Params = Promise<{ datasetId: string }>;
type SearchParams = Promise<{ run?: string }>;

export async function generateMetadata({ params }: { params: Params }): Promise<Metadata> {
  const { datasetId } = await params;
  const detail = await getDatasetDetail(datasetId);
  return { title: detail ? detail.dataset.label : "Dataset" };
}

function SectionHeading({ children }: { children: React.ReactNode }) {
  return <h2 className="text-sm font-semibold">{children}</h2>;
}

async function RunLog({ runId }: { runId: string }) {
  const events = await getSyncEvents(runId);
  return (
    <div className="flex flex-col gap-2">
      <div className="flex items-center justify-between">
        <SectionHeading>Run log</SectionHeading>
        <span className="text-muted-foreground font-mono text-xs">{runId}</span>
      </div>
      <SyncEventsLog events={events} />
    </div>
  );
}

export default async function DatasetDetailPage({
  params,
  searchParams,
}: {
  params: Params;
  searchParams: SearchParams;
}) {
  await requireAdmin();
  const { datasetId } = await params;
  const { run: runId } = await searchParams;

  const detail = await getDatasetDetail(datasetId);
  if (!detail) notFound();

  const { dataset, runs, versions, fields, profile } = detail;
  const latestVersion = versions[0];
  const driftUnresolved =
    dataset.health === "schema_drift" && latestVersion && !latestVersion.acceptedAt;

  return (
    <div className="flex flex-col gap-6 p-4 sm:p-6">
      <Link
        href="/admin/sync"
        className="text-muted-foreground hover:text-foreground inline-flex w-fit items-center gap-1.5 text-sm"
      >
        <ArrowLeft className="size-3.5" aria-hidden />
        Sync activity
      </Link>

      <PageHeader
        title={dataset.label}
        description={`${dataset.externalId} · discovered ${format(dataset.discoveredAt, "d MMM yyyy")}`}
        actions={<DatasetDetailActions datasetId={dataset.id} status={dataset.status} />}
      />

      <div className="flex flex-wrap items-center gap-3">
        <HealthPill health={dataset.health} detail={dataset.healthDetail} />
        <span className="text-muted-foreground text-sm capitalize">{dataset.status}</span>
        <span className="text-muted-foreground text-sm">
          <RelativeTime value={dataset.lastSyncedAt} fallback="never synced" /> · last sync
        </span>
        <span className="text-muted-foreground font-mono text-sm tabular-nums">
          {formatCount(dataset.itemCount)} items
        </span>
      </div>

      <div className="border-border flex flex-col gap-3 rounded-xl border p-4">
        <SectionHeading>Sync schedule</SectionHeading>
        <SyncIntervalForm
          datasetId={dataset.id}
          autoSyncEnabled={dataset.autoSyncEnabled}
          syncIntervalSeconds={dataset.syncIntervalSeconds}
        />
      </div>

      <div className="border-border flex flex-col gap-3 rounded-xl border p-4">
        <SectionHeading>Mapping profile</SectionHeading>
        {profile ? (
          <div className="flex flex-wrap items-center justify-between gap-3">
            <div className="text-sm">
              <div className="font-medium">{profile.name}</div>
              <div className="text-muted-foreground text-xs">
                {profile.autoGenerated ? "Auto-generated" : "Curated"}
                {profile.confidence !== null && ` · confidence ${Math.round(profile.confidence * 100)}%`}
                {profile.approvedAt ? " · approved" : " · awaiting approval"}
              </div>
            </div>
            {!profile.approvedAt && (
              <ApproveMappingProfileButton profileId={profile.id} datasetId={dataset.id} />
            )}
          </div>
        ) : (
          <p className="text-muted-foreground text-sm">
            No mapping profile yet — items are stored but not normalized into leads.
          </p>
        )}
      </div>

      <div className="border-border flex flex-col gap-3 rounded-xl border p-4">
        <SectionHeading>Schema versions</SectionHeading>
        {versions.length === 0 ? (
          <p className="text-muted-foreground text-sm">No schema captured yet.</p>
        ) : (
          <ul className="flex flex-col gap-2">
            {versions.map((version) => {
              const diff = version.schemaDiff as SchemaDiff | null;
              const drifted = version.id === latestVersion?.id && driftUnresolved;
              return (
                <li
                  key={version.id}
                  className="border-border/60 flex flex-wrap items-start justify-between gap-3 rounded-lg border p-3 text-sm"
                >
                  <div>
                    <div className="flex items-center gap-2 font-medium">
                      v{version.versionNo}
                      {drifted && (
                        <span className="bg-[var(--health-drift-bg)] text-[var(--health-drift-fg)] rounded-full px-2 py-0.5 text-xs">
                          Drift — needs review
                        </span>
                      )}
                      {version.acceptedAt && !drifted && (
                        <span className="text-muted-foreground text-xs">accepted</span>
                      )}
                    </div>
                    <div className="text-muted-foreground mt-1 text-xs">
                      <RelativeTime value={version.capturedAt} /> · {formatCount(version.itemCount)}{" "}
                      items
                      {diff && (diff.added.length > 0 || diff.removed.length > 0 || diff.typeChanged.length > 0) && (
                        <>
                          {" · "}
                          {diff.added.length > 0 && `+${diff.added.length} added `}
                          {diff.removed.length > 0 && `-${diff.removed.length} removed `}
                          {diff.typeChanged.length > 0 && `${diff.typeChanged.length} type changed`}
                        </>
                      )}
                    </div>
                  </div>
                  {drifted && (
                    <AcceptSchemaVersionButton versionId={version.id} datasetId={dataset.id} />
                  )}
                </li>
              );
            })}
          </ul>
        )}
      </div>

      <div className="flex flex-col gap-3">
        <SectionHeading>Discovered fields</SectionHeading>
        {fields.length === 0 ? (
          <EmptyState title="No fields discovered yet" />
        ) : (
          <DataTable minWidth="min-w-[640px]">
            <DataTableHead>
              <th>Path</th>
              <th className="w-24">Type</th>
              <th className="w-24">Fill rate</th>
              <th className="w-28">Cardinality</th>
              <th className="w-24">Facetable</th>
            </DataTableHead>
            <tbody>
              {fields.map((field) => (
                <tr key={field.id} className="border-border border-t">
                  <td className="px-3 py-2 font-mono text-xs">{field.path}</td>
                  <td className="text-muted-foreground px-3 py-2 text-xs">{field.inferredType}</td>
                  <td className="px-3 py-2 font-mono text-xs tabular-nums">
                    {Math.round(field.fillRate * 100)}%
                  </td>
                  <td className="px-3 py-2 font-mono text-xs tabular-nums">{field.cardinality}</td>
                  <td className="px-3 py-2 text-xs">
                    {(field.facetableOverride ?? field.facetable) ? "Yes" : "No"}
                  </td>
                </tr>
              ))}
            </tbody>
          </DataTable>
        )}
      </div>

      <div className="flex flex-col gap-3">
        <SectionHeading>Run history</SectionHeading>
        <SyncRunsTable runs={runs.map((r) => ({ ...r, datasetId: dataset.id, datasetLabel: dataset.label }))} />
      </div>

      {runId && (
        <Suspense fallback={<TableSkeleton />}>
          <RunLog runId={runId} />
        </Suspense>
      )}
    </div>
  );
}
