import { sql } from "drizzle-orm";
import {
  boolean,
  index,
  integer,
  jsonb,
  pgTable,
  real,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from "drizzle-orm/pg-core";
import {
  datasetHealthEnum,
  datasetStatusEnum,
  leadRecordKindEnum,
  platformEnum,
  sourceKindEnum,
} from "./enums";
import type { FieldProfile, MappingRules } from "@/domain/dataset/types";

/** A connector instance. Replaces APIFY_ACTOR_ID / APIFY_DATASET_ID env vars. */
export const sources = pgTable(
  "sources",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    kind: sourceKindEnum("kind").notNull(),
    name: text("name").notNull(),
    /** Connector-specific settings, e.g. { actorIds: [...], namePatterns: [...] }. */
    config: jsonb("config").$type<Record<string, unknown>>().notNull().default({}),
    enabled: boolean("enabled").notNull().default(true),
    lastDiscoveredAt: timestamp("last_discovered_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex("sources_kind_name_key").on(t.kind, t.name)],
);

/**
 * Declarative field mapping from a discovered payload shape onto the canonical lead.
 * Stored as data so a shape change is an admin edit + backfill, never a deploy.
 */
export const mappingProfiles = pgTable(
  "mapping_profiles",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    name: text("name").notNull(),
    sourceKind: sourceKindEnum("source_kind").notNull(),
    /** What the payload *is* — a post, a like, a comment. Carried onto every lead it produces. */
    recordKind: leadRecordKindEnum("record_kind").notNull().default("content_post"),
    /** Which platform this profile's identity id (authorExternalId) belongs to — facebookId vs instagramId at merge time. */
    platform: platformEnum("platform").notNull().default("facebook"),
    version: integer("version").notNull().default(1),
    rules: jsonb("rules").$type<MappingRules>().notNull(),
    /**
     * Paths that must all be present for this curated profile to claim a newly
     * discovered dataset. A hand-verified profile always beats an auto-proposal,
     * which is what stops a confident-but-wrong guess from taking over a dataset
     * we already understand.
     */
    matchPaths: text("match_paths").array().notNull().default(sql`'{}'::text[]`),
    /** Unmapped discovered fields are preserved into lead.attributes when true. */
    passthrough: boolean("passthrough").notNull().default(true),
    autoGenerated: boolean("auto_generated").notNull().default(false),
    /** 0..1 confidence of an auto-proposal; below the floor it needs admin review. */
    confidence: real("confidence"),
    approvedAt: timestamp("approved_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex("mapping_profiles_name_version_key").on(t.name, t.version)],
);

export const datasets = pgTable(
  "datasets",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    sourceId: uuid("source_id")
      .notNull()
      .references(() => sources.id, { onDelete: "cascade" }),
    /** Upstream identifier (Apify dataset id). */
    externalId: text("external_id").notNull(),
    name: text("name"),
    title: text("title"),
    /** Upstream actor/workflow that produced it — lineage for comparison. */
    producerId: text("producer_id"),
    producerRunId: text("producer_run_id"),

    status: datasetStatusEnum("status").notNull().default("active"),
    health: datasetHealthEnum("health").notNull().default("unknown"),
    healthDetail: text("health_detail"),
    healthCheckedAt: timestamp("health_checked_at", { withTimezone: true }),

    itemCount: integer("item_count").notNull().default(0),
    /** Upstream mtime — the primary change signal (webhooks are only an accelerant). */
    remoteModifiedAt: timestamp("remote_modified_at", { withTimezone: true }),
    remoteCreatedAt: timestamp("remote_created_at", { withTimezone: true }),

    mappingProfileId: uuid("mapping_profile_id").references(() => mappingProfiles.id, {
      onDelete: "set null",
    }),
    schemaFingerprint: text("schema_fingerprint"),

    /** Incremental watermark: { lastOffset, lastItemCount, lastSyncedAt }. */
    syncCursor: jsonb("sync_cursor").$type<Record<string, unknown>>().notNull().default({}),
    autoSyncEnabled: boolean("auto_sync_enabled").notNull().default(true),
    syncIntervalSeconds: integer("sync_interval_seconds").notNull().default(900),
    consecutiveFailures: integer("consecutive_failures").notNull().default(0),
    lastSyncedAt: timestamp("last_synced_at", { withTimezone: true }),
    nextSyncDueAt: timestamp("next_sync_due_at", { withTimezone: true }),

    discoveredAt: timestamp("discovered_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex("datasets_source_external_key").on(t.sourceId, t.externalId),
    index("datasets_status_idx").on(t.status),
    index("datasets_due_idx").on(t.nextSyncDueAt),
  ],
);

/** Immutable snapshot captured whenever the schema fingerprint or item count moves. */
export const datasetVersions = pgTable(
  "dataset_versions",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    datasetId: uuid("dataset_id")
      .notNull()
      .references(() => datasets.id, { onDelete: "cascade" }),
    versionNo: integer("version_no").notNull(),
    itemCount: integer("item_count").notNull(),
    schemaFingerprint: text("schema_fingerprint").notNull(),
    fieldProfile: jsonb("field_profile").$type<FieldProfile[]>().notNull(),
    /** Human-readable diff vs the previous version, computed at capture time. */
    schemaDiff: jsonb("schema_diff").$type<Record<string, unknown>>(),
    acceptedAt: timestamp("accepted_at", { withTimezone: true }),
    capturedAt: timestamp("captured_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex("dataset_versions_no_key").on(t.datasetId, t.versionNo)],
);

/** Inferred schema per dataset. Drives dynamic filters, columns and chart dimensions. */
export const fieldCatalog = pgTable(
  "field_catalog",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    datasetId: uuid("dataset_id")
      .notNull()
      .references(() => datasets.id, { onDelete: "cascade" }),
    path: text("path").notNull(),
    inferredType: text("inferred_type").notNull(),
    nullable: boolean("nullable").notNull().default(true),
    fillRate: real("fill_rate").notNull().default(0),
    cardinality: integer("cardinality").notNull().default(0),
    sampleValues: jsonb("sample_values").$type<unknown[]>().notNull().default([]),
    /** Auto-flagged from cardinality + fill rate; admin can override. */
    facetable: boolean("facetable").notNull().default(false),
    facetableOverride: boolean("facetable_override"),
    mappedTo: text("mapped_to"),
    firstSeenAt: timestamp("first_seen_at", { withTimezone: true }).notNull().defaultNow(),
    lastSeenAt: timestamp("last_seen_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex("field_catalog_dataset_path_key").on(t.datasetId, t.path)],
);

/**
 * Canonicalises observed location strings ("changgu", "Denpasar, Bali") onto one
 * label so dynamic location filters don't fragment into near-duplicates.
 */
export const locationAliases = pgTable(
  "location_aliases",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    alias: text("alias").notNull(),
    canonical: text("canonical").notNull(),
    region: text("region"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex("location_aliases_alias_key").on(t.alias)],
);

export type SourceRow = typeof sources.$inferSelect;
export type DatasetRow = typeof datasets.$inferSelect;
export type DatasetVersionRow = typeof datasetVersions.$inferSelect;
export type MappingProfileRow = typeof mappingProfiles.$inferSelect;
export type FieldCatalogRow = typeof fieldCatalog.$inferSelect;
