import "server-only";
import { and, eq } from "drizzle-orm";
import { db, schema } from "@/infrastructure/db/client";
import { getConnector } from "@/infrastructure/connectors/registry";
import { inferSchema } from "@/domain/dataset/schema-inference";
import { proposeMapping } from "@/domain/dataset/mapping-proposal";
import { applyMapping } from "@/domain/dataset/mapping";
import { classifyWithRules } from "@/domain/scoring/rules-classifier";
import { getLexiconForCategory } from "@/domain/scoring/lexicon-registry";
import type { LeadIntent } from "@/domain/scoring/types";

export interface SourcePreviewItem {
  authorName: string | null;
  body: string;
  listingTitle: string | null;
  intent: LeadIntent;
}

export interface SourcePreviewResult {
  items: SourcePreviewItem[];
  /** True when nothing curated claimed this shape and the mapping is a best guess — not a reason to block the preview, just to say so. */
  isGuessedMapping: boolean;
}

/**
 * A one-time, read-only sample classification for the onboarding wizard's
 * "here's what we found" step — composes the same pure functions the real
 * pipeline does (`applyMapping`, `classifyWithRules`, curated-profile
 * matching by `matchPaths`, `proposeMapping` as the fallback), in the same
 * order `resolveMappingProfile`/`processRawRecords` use, but never writes
 * `raw_records`, `mapping_profiles`, `lead_appearances`, or anything else —
 * `fetchItems` is a pure read and every mapping/classify step here is
 * DB-free. Confirming the wizard calls the real `runSync` action instead,
 * which persists through the normal pipeline.
 */
export async function previewSource(companyId: string, datasetId: string, sampleSize = 3): Promise<SourcePreviewResult> {
  const [dataset] = await db()
    .select({ id: schema.datasets.id, externalId: schema.datasets.externalId, sourceId: schema.datasets.sourceId })
    .from(schema.datasets)
    .where(and(eq(schema.datasets.id, datasetId), eq(schema.datasets.companyId, companyId)))
    .limit(1);
  if (!dataset) throw new Error("Dataset not found.");

  const [company] = await db()
    .select({ category: schema.companies.category })
    .from(schema.companies)
    .where(eq(schema.companies.id, companyId))
    .limit(1);
  const lexicon = getLexiconForCategory(company?.category ?? "other");

  const [source] = await db()
    .select({ kind: schema.sources.kind })
    .from(schema.sources)
    .where(eq(schema.sources.id, dataset.sourceId))
    .limit(1);
  if (!source) throw new Error("Source not found.");

  const connector = getConnector(source.kind);
  const page = await connector.fetchItems(dataset.externalId, 0, sampleSize, { companyId });
  if (page.items.length === 0) return { items: [], isGuessedMapping: false };

  const fieldProfiles = inferSchema(page.items);
  const paths = new Set(fieldProfiles.map((p) => p.path));

  // Same claim rule as `resolveMappingProfile` in sync-dataset.ts: a curated,
  // hand-verified profile always wins over a guess — read-only here, no
  // auto-generated profile row gets inserted the way a real sync would.
  const curated = await db()
    .select()
    .from(schema.mappingProfiles)
    .where(and(eq(schema.mappingProfiles.sourceKind, source.kind), eq(schema.mappingProfiles.autoGenerated, false)));
  const claimed = curated
    .filter((p) => p.matchPaths.length > 0 && p.matchPaths.every((path) => paths.has(path)))
    .sort((a, b) => b.matchPaths.length - a.matchPaths.length)[0];

  const { rules, passthrough, recordKind, isGuessedMapping } = claimed
    ? { rules: claimed.rules, passthrough: claimed.passthrough, recordKind: claimed.recordKind, isGuessedMapping: false }
    : (() => {
        const proposal = proposeMapping(fieldProfiles);
        return { rules: proposal.rules, passthrough: true, recordKind: "content_post" as const, isGuessedMapping: true };
      })();

  const items = page.items.map((raw) => {
    const normalized = applyMapping(raw, rules, { passthrough });
    const classification = classifyWithRules(
      {
        body: normalized.body,
        listingTitle: normalized.listingTitle,
        locationRaw: normalized.locationRaw,
        priceRaw: normalized.priceRaw,
        bedrooms: normalized.bedrooms,
        bathrooms: normalized.bathrooms,
        engagement: normalized.engagement,
        sourceGroup: normalized.sourceGroup,
        postedAt: normalized.postedAt,
        recordKind,
      },
      lexicon,
    );
    return {
      authorName: normalized.authorName,
      body: normalized.body,
      listingTitle: normalized.listingTitle,
      intent: classification.intent,
    };
  });

  return { items, isGuessedMapping };
}

/** For the wizard's confirmation copy — "184 leads collected from this source so far" style context isn't needed pre-sync, just the target's own name. */
export async function getDatasetLabel(companyId: string, datasetId: string): Promise<string | null> {
  const [row] = await db()
    .select({ name: schema.datasets.name, title: schema.datasets.title, externalId: schema.datasets.externalId })
    .from(schema.datasets)
    .where(and(eq(schema.datasets.id, datasetId), eq(schema.datasets.companyId, companyId)))
    .limit(1);
  if (!row) return null;
  return row.title ?? row.name ?? `Unnamed (${row.externalId.slice(0, 8)})`;
}
